Task WDP230601-13
matwjablonski/wdp-2306-01 pull request #12
Opened 2023-06-08 20:54 UTC by jerzy-jarczynski

[https://projects.kodilla.com/browse/WDP230601-13](https://projects.kodilla.com/browse/WDP230601-13)

**Swipeable - obsługa swipe**

- brakowało komponentu-wrappera, który umożliwiałby funkcję swipe dla swoich elementów children
- dodałem komponent Swipeable w common
- nie udało mi się wykorzystać react-swipeable, więc wykorzystałem natywne eventy touch
- umieściłem zawartość zwracaną przez NewFurniture w Swipeable. Dodałem funkcję akcji. Zrefaktoryzowałem kod.
- usunięcie paczki react-swipeable dodałem w osobnym commicie.

2023-06-09 07:14 UTC, matwjablonski requested changes

2023-06-09 07:14 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  handleCategoryChange = newCategory => {
dlaczego zastąpiłeś metody na arrow functions? w class'ach w ja nie powinno się używać arrow-functions jako metody

2023-06-09 07:14 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +      activePage * 8,
co to 8? MagicNumber ;)

2023-06-09 09:14 UTC, jerzy-jarczynski commented on src/components/features/NewFurniture/NewFurniture.js
> +  handleCategoryChange = newCategory => {
Przywróciłem wcześniejszą wersję bez arrow functions.

2023-06-09 09:14 UTC, jerzy-jarczynski commented on src/components/features/NewFurniture/NewFurniture.js
> +      activePage * 8,
Dodałem wartość 8 do stanu komponentu.

2023-06-10 08:29 UTC, ZukAd14 submitted a review, later dismissed

2023-06-10 18:45 UTC, Blackbirdev submitted a review, later dismissed

2023-06-14 21:15 UTC, ZukAd14 approved these changes

2023-06-15 06:58 UTC, matwjablonski approved these changes

2023-06-15 06:58 UTC, merged