Add settings for animation and use it for all hover elements
matwjablonski/wdp-2306-01 pull request #13
Opened 2023-06-09 07:23 UTC by Blackbirdev

https://projects.kodilla.com/browse/WDP230601-9

**Dodanie jednolitych animacji na hover**

- Dodałem animacje(linków, tła, icon i przycisków) do  zmiennych w ustawieniach;
- Wykorzystałem keyframes do ustawienia animacji(kolor tła, czas, liczba iteracji animacji, pulsowanie przycisku) dla każdego elementu, który można kliknąć(MenuBar, TopBar, NewFurniture, Button, Footer);

2023-06-10 08:33 UTC, ZukAd14 requested changes
Ładnie to wygląda, dorzuć commity z poprawionym package.json i dla mnie w porządku

2023-06-12 06:31 UTC, matwjablonski requested changes

2023-06-12 06:31 UTC, matwjablonski commented on package.json
> +    "start:react": "react-scripts --openssl-legacy-provider start",
zamiast --openssl-legacy-provider możecie spróbować podbić wersję react-scripts do 5

2023-06-12 06:31 UTC, matwjablonski commented on src/components/layout/Footer/Footer.module.scss
> +
coś Ci się tutaj zostało :)

2023-06-12 06:31 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +  :global(.container)> :global(.row) {
ta spacja była ok :)

2023-06-12 06:31 UTC, matwjablonski commented on src/styles/settings.scss
> +$animation-icon: rgb(255, 208, 0);
to jest kolor a z nazwy nie wynika :)

2023-06-12 06:31 UTC, matwjablonski commented on src/styles/settings.scss
> +$animation-iteration-count: 1;
może warto tutaj dodać default do nazwy? :)

2023-06-12 06:31 UTC, matwjablonski commented on src/styles/settings.scss
> +// Set number of iteration or "infinite"
komentarze wydają mi się zbędne, w zasadzie nie jest to narzędzie, które będzie konfigurowane przez innych.

2023-06-19 17:24 UTC, closed without merging