[ WDP230601-16 ] RWD dla FeatureBoxes
matwjablonski/wdp-2306-01 pull request #14
Opened 2023-06-09 10:41 UTC by wilgakuba

https://projects.kodilla.com/browse/WDP230601-16

-Za pomocą bootstrap zmieniłem boksy tak, aby mieć  je w 2 rzędach, po 2 elementy w każdym na ekranach mniejszych niż large(lg),
- na ekranach large i większych będą ustawiać się w 1 rzędzie i dostosowywać do szerokości ekranu.

2023-06-09 14:26 UTC, Blackbirdev reviewed
po odpaleniu strony na telefonie jest różnica w wysokości elementów( te po prawej stronie mają większą wysokość)

2023-06-10 08:39 UTC, ZukAd14 requested changes
Tak jak pisze Bartek, różnica w wysokościach jest widoczna dla ekranów o szerokości poniżej 475px [Podgląd](https://postimg.cc/t1bLK4qC)

2023-06-11 21:27 UTC, ZukAd14 approved these changes

2023-06-12 06:32 UTC, matwjablonski approved these changes

2023-06-12 06:32 UTC, merged