[ WDP230601-17 ] RWD - sekcja NewFurniture
matwjablonski/wdp-2306-01 pull request #15
Opened 2023-06-09 11:26 UTC by wilgakuba

https://projects.kodilla.com/browse/WDP230601-17

-nadałem pozycjonowanie product boksów według wskazówek w zadaniu,
-dopasowałem ich wielkości na różnych szerokościach,
-zmieniłem wielkość czcionki tak aby na buttonie tekst zawsze wyświetlał się w jednej linii.

2023-06-09 14:30 UTC, Blackbirdev submitted a review, later dismissed

2023-06-10 08:13 UTC, iiimoood approved these changes

2023-06-10 08:42 UTC, ZukAd14 approved these changes

2023-06-10 12:30 UTC, jerzy-jarczynski approved these changes

2023-06-12 06:34 UTC, matwjablonski requested changes

2023-06-12 06:34 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +// Media
co daje ten komentarz?

2023-06-12 11:25 UTC, Blackbirdev approved these changes

2023-06-13 18:28 UTC, matwjablonski approved these changes

2023-06-13 18:28 UTC, merged