[WDP230601-12] Porównywanie produktów
matwjablonski/wdp-2306-01 pull request #17
Opened 2023-06-10 10:18 UTC by ZukAd14

[Podgląd zadania w Jira](https://projects.kodilla.com/browse/WDP230601-12)

-Dodałem porównywarkę na dole strony wraz z buttonem 'compare'
-Po dodaniu produktu wyświetlają się zdjęcia jako miniaturki
-Po najechaniu na miniaturkę wyświetla się ikonka do usuwania
-Można dodać maxymalnie cztery produkty
-Po odświeżeniu strony komponent się resetuję tak jak jest w zadaniu

Jedyne z czym nie jestem w stanie sobie poradzić to usuwanie produktów z porównania, rwę już włosy z głowy... Przeglądałem repo, które podrzucił @jerzy-jarczynski, jednak nie byłem w stanie tego zaimplementować. Nie da się wykorzystać hooka useState w NewFurniture bez przebudowy całego komponentu na funkcyjny. Proszę o pomoc bo utknę tu na amen

2023-06-12 06:43 UTC, matwjablonski requested changes

2023-06-12 06:43 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  compare = [];
tak nie możemy zrobić. to jest komponent reactowy a zatem taka konstrukcja spowoduje ze nie będzie miał nad tą wartością kontroli react - sugeruję albo skorzystać ze stanu, albo z reduxa

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.js
> +  const deleteProduct = id => {
wolna linia powyżej

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.js
> +  if (compareState.length === 0) return <div className={styles.invisible}></div>;
użyj proszę {}

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.js
> +  if (compareState.length === 0) return <div className={styles.invisible}></div>;
jak nie dajemy dzieci to zamykamy bezpośrednio `<div className={styles.invisible} />`

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.js
> +  else if (compareState !== undefined && compareState !== [] && compareState !== '')
a co zwróci komponent jeśli warunki nie zostaną spełnione?

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.js
> +              <h1 className={styles.delete}>X</h1>
h1 do usuwania to chyba za dużo :)

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.js
> +                src={`${process.env.PUBLIC_URL}/images/products/${compares.name}.jpeg`}
wszystkie zdjęcia zawsze mają rozszerzenie jpeg?

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.module.scss
> +    .box:nth-child(even) {
wolna linia powyżej

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.module.scss
> +    &:hover {
jw

2023-06-12 06:43 UTC, matwjablonski commented on src/components/layout/CompareBar/CompareBar.module.scss
> +            opacity: 0.4;
wcięcia

2023-06-13 08:19 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.js
> +  const deleteProduct = id => {
poprawione

2023-06-13 08:19 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.module.scss
> +    .box:nth-child(even) {
poprawione

2023-06-13 08:19 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.module.scss
> +    &:hover {
poprawione

2023-06-13 08:19 UTC, ZukAd14 commented on src/components/features/NewFurniture/NewFurniture.js
> +  compare = [];
Poprawione, skorzystałem ze stanu

2023-06-13 08:20 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.js
> +  if (compareState.length === 0) return <div className={styles.invisible}></div>;
Poprawione

2023-06-13 08:21 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.js
> +  else if (compareState !== undefined && compareState !== [] && compareState !== '')
Nie jestem pewien czy o to chodziło ale dodałem kończącego 'elsa' na końcu, jeżeli chodziło o coś innego doprecyzuj proszę to poprawię ;)

2023-06-13 08:21 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.js
> +                src={`${process.env.PUBLIC_URL}/images/products/${compares.name}.jpeg`}
nakombinowałem, ale poprawione

2023-06-13 08:21 UTC, ZukAd14 commented on src/components/layout/CompareBar/CompareBar.module.scss
> +            opacity: 0.4;
poprawione

2023-06-15 08:19 UTC, matwjablonski requested changes
<img width="444" alt="Zrzut ekranu 2023-06-15 o 10 17 50" src="https://github.com/matwjablonski/wdp-2306-01/assets/20933197/427e5ea0-9a61-487f-9780-989ff4217a9f">

1) skąd wiadomo że dany produkt został wybrany? przycisk powinien być jakoś oznaczony
2) mogę wybrać 2 razy ten sam produkt do porównania
3) przyciski do dodawania do porównywarki powinny być wyszarzone gdy nie ma możliwości dodania produktu do porównywarki

2023-06-16 05:49 UTC, jerzy-jarczynski submitted a review, later dismissed

2023-06-17 16:35 UTC, jerzy-jarczynski commented on package.json
> +    "shortid": "^2.2.16"
w kursie jest używane shortid, ale są komunikaty, że ta paczka jest deprecated i w zamian poleca się nanoid
Jest równie proste w obsłudze, a ponoć bezpieczniejsze. W szczegóły się nie wbgłębiałem.

2023-06-17 16:47 UTC, jerzy-jarczynski commented on src/components/common/ProductBox/ProductBox.js
> +}) => {
Można by to zapisać z operatorem ...w jednej linijce, żeby tak nie rozpychało kodu

2023-06-17 17:03 UTC, jerzy-jarczynski reviewed
Dam approve po poprawce bordera na wybranym elemencie :)

2023-06-18 09:03 UTC, ZukAd14 commented on src/components/common/ProductBox/ProductBox.js
> +}) => {
To akurat sprawka Eslinta albo Prettiera, nie jestem pewien którego. Też mi się taki zapis nie podoba ale po zmianie na jedną linię i ponownym commicie wraca do takiego stanu

2023-06-18 09:04 UTC, ZukAd14 commented on package.json
> +    "shortid": "^2.2.16"
Zmieniłem na nanoid, trzeba było wykorzystać wersję 3.0.0 zamiast najnowszej bo coś się gryzło z nodem w wersji 16

2023-06-18 09:05 UTC, ZukAd14 commented
> Dam approve po poprawce bordera na wybranym elemencie :)

Border jest poprawiony, Mateusz zgłaszał że rozpycha elementy więc zmieniłem na `outline`, nie było propozycji innego efektu więc zostały kropki

2023-06-18 18:22 UTC, iiimoood submitted a review, later dismissed

2023-06-19 18:41 UTC, Blackbirdev approved these changes

2023-06-20 16:26 UTC, jerzy-jarczynski approved these changes

2023-06-20 19:54 UTC, Mikaaa366 approved these changes

2023-06-20 20:29 UTC, merged