Task WDP230601-14
matwjablonski/wdp-2306-01 pull request #21
Opened 2023-06-10 20:01 UTC by jerzy-jarczynski

https://projects.kodilla.com/browse/WDP230601-14

**RWD - menu główne**

- menu główne nie składało się dobrze na mniejszych rozdzielczościach.
- dodałem style dla wyglądu mobilnego z rozwijanym menu.
- dodałem style dla wyglądu pośredniego (tablet) z wyszukiwarką pod menu
- będę wdzięczny za poprawki estetyczne dotyczące zwłaszcza rozwijanego menu na mobile

2023-06-12 06:57 UTC, matwjablonski requested changes

2023-06-12 06:57 UTC, matwjablonski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +        border-left: 0px solid $pure-black ;
0 bez jednostek

2023-06-14 18:50 UTC, jerzy-jarczynski commented on src/components/layout/MenuBar/MenuBar.module.scss
> +        border-left: 0px solid $pure-black ;
Poprawione

2023-06-14 21:17 UTC, ZukAd14 submitted a review, later dismissed

2023-06-16 05:28 UTC, jerzy-jarczynski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +  &>* {
Poprawiłem spację na innym komputerze

2023-06-16 07:55 UTC, Blackbirdev approved these changes

2023-06-16 11:44 UTC, iiimoood approved these changes

2023-06-20 10:49 UTC, closed without merging