[TASK-WDP230601-15] - RWD TopBar i banner
matwjablonski/wdp-2306-01 pull request #23
Opened 2023-06-11 18:18 UTC by Blackbirdev

Jira: https://projects.kodilla.com/browse/WDP230601-15

- dodałem media queries do TopBar i banner na wersję mobilną;

2023-06-12 07:01 UTC, matwjablonski requested changes
projekt się nie buduje - spróbuj zbudować go lokalnie i rozwiązać problem

2023-06-12 07:01 UTC, matwjablonski commented on src/components/layout/TopBar/TopBar.module.scss
> +      .icon {
podobnie tutaj - czy potrzebujemy tutaj specyficzności tak złożonej?

2023-06-13 08:42 UTC, ZukAd14 approved these changes

2023-06-13 21:36 UTC, ZukAd14 submitted a review, later dismissed

2023-06-14 16:49 UTC, Mikaaa366 approved these changes

2023-06-15 07:06 UTC, matwjablonski requested changes
<img width="318" alt="Zrzut ekranu 2023-06-15 o 09 04 33" src="https://github.com/matwjablonski/wdp-2306-01/assets/20933197/463c2297-317f-4e9a-b357-897ed45b8f44">
<img width="180" alt="Zrzut ekranu 2023-06-15 o 09 05 43" src="https://github.com/matwjablonski/wdp-2306-01/assets/20933197/7cbe317f-74db-4098-b6bb-6479a50b07cc">
<img width="318" alt="Zrzut ekranu 2023-06-15 o 09 05 30" src="https://github.com/matwjablonski/wdp-2306-01/assets/20933197/b94dc873-2b12-446a-8072-7448778db521">

wersja mobilna na chrome

2023-06-16 14:32 UTC, jerzy-jarczynski submitted a review, later dismissed

2023-06-16 15:41 UTC, ZukAd14 submitted a review, later dismissed

2023-06-19 12:02 UTC, iiimoood approved these changes

2023-06-19 14:32 UTC, ZukAd14 submitted a review, later dismissed

2023-06-19 18:09 UTC, jerzy-jarczynski approved these changes

2023-06-19 18:13 UTC, merged