Task 11
matwjablonski/wdp-2306-01 pull request #25
Opened 2023-06-12 21:27 UTC by Mikaaa366

Link:
https://projects.kodilla.com/browse/WDP230601-11
Opis:
Dodałam funkcjonalność dla guzika ulubione, tak aby przy odświeżeniu co najmniej jeden produkt był ulubiony

2023-06-13 09:02 UTC, ZukAd14 submitted a review, later dismissed

2023-06-13 10:00 UTC, iiimoood submitted a review, later dismissed
Według mnie ok, do zmiany ewentualnie zmienne kolorów dla a.Favorite.

2023-06-13 21:37 UTC, ZukAd14 approved these changes

2023-06-14 09:04 UTC, Mikaaa366 commented
> Według mnie ok, do zmian Wezmę zmienne kolory dla a.Favorite.

ale na jaki? bo w poleceniu było, żeby dodać taki jak dla hover, więc myślałam, że o ten chodzi.

2023-06-14 19:32 UTC, jerzy-jarczynski submitted a review, later dismissed

2023-06-16 05:50 UTC, jerzy-jarczynski submitted a review, later dismissed

2023-06-16 06:55 UTC, matwjablonski requested changes

2023-06-16 06:55 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +  const productId = id;
po co to przypisanie?

2023-06-16 06:55 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +            <a key={i} href='#'>
semantycznie to nic nie robi i nie prowadzi do nikąd a zatem średni to link :)

2023-06-17 19:41 UTC, Mikaaa366 commented on src/components/common/ProductBox/ProductBox.js
> +            <a key={i} href='#'>
racja, już poprawiłam

2023-06-17 19:45 UTC, Mikaaa366 commented on src/components/common/ProductBox/ProductBox.js
> +  const productId = id;
w zasadzie niepotrzebne, poprawię

2023-06-18 09:16 UTC, ZukAd14 submitted a review, later dismissed

2023-06-19 18:08 UTC, jerzy-jarczynski submitted a review, later dismissed

2023-06-19 18:11 UTC, Blackbirdev approved these changes

2023-06-19 18:23 UTC, ZukAd14 approved these changes

2023-06-19 18:28 UTC, iiimoood approved these changes

2023-06-19 18:28 UTC, jerzy-jarczynski approved these changes

2023-06-19 18:29 UTC, merged