WDP230601-30
matwjablonski/wdp-2306-01 pull request #26
Opened 2023-06-14 16:41 UTC by Mikaaa366

- dodałam komponent brand dla sekcji z markami,
- ostylowałam wg designu,

2023-06-16 05:56 UTC, jerzy-jarczynski requested changes
Moim zdaniem trzeba poprawić kod :)

2023-06-16 05:56 UTC, jerzy-jarczynski commented on src/components/layout/Brands/Brands.module.scss
> +    border-top: 1px solid $light-gray;
do settings trzeba by dodać dową sekcję, i zamienić te zmienne na takie deklarowane dla komponmentu, żeby było zgodnie z przyjętą konwencją i wielkim komentarzem 

// DO NOT USE THIS! :D

2023-06-16 05:56 UTC, jerzy-jarczynski commented on src/redux/initialState.js
> +    { id: 6, source: '/images/brands/brand 6.png', brandName: 'brand 6' },
Czy source nie powinno być zaciągane z public?

Jest ten zapis ze zmienną ENV

2023-06-17 20:11 UTC, Mikaaa366 commented on src/components/layout/Brands/Brands.module.scss
> +    border-top: 1px solid $light-gray;
tak, tak, już wiem, poprawię :)

2023-06-19 20:48 UTC, Mikaaa366 commented on src/redux/initialState.js
> +    { id: 6, source: '/images/brands/brand 6.png', brandName: 'brand 6' },
poprawione :)

2023-06-19 21:08 UTC, ZukAd14 approved these changes

2023-06-20 10:51 UTC, jerzy-jarczynski approved these changes

2023-06-20 10:56 UTC, Blackbirdev approved these changes

2023-06-20 11:19 UTC, merged