[ WDP230601-27 ] - Galeria- komponent
matwjablonski/wdp-2306-01 pull request #29
Opened 2023-06-15 16:40 UTC by wilgakuba

https://projects.kodilla.com/browse/WDP230601-27

-dodałem komponent galerii dzieląc go na dwie części:
  -statyczny element, niezwiązany ze sliderem po lewej,
  -gallery slider, któremu w przyszłości nadaje się funkcjonalność,
-ostylowałem wszystko.

2023-06-16 06:07 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.js
> +        <div className={clsx(styles.buttons, styles.tooltip)}>
To nie jest błąd, ale clsx możemy unikać za pomocą zapisu ES6

tutaj byłoby to
`${styles.buttons} ${styles.tooltip}`

2023-06-16 06:11 UTC, jerzy-jarczynski requested changes
Należy ocenić, czy nie można poprawić kodu

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +    background-color: rgba(202, 201, 191, 0.8);
wrzuciłbym to do zmiennej w settings

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +  background-color: $text-color;
Tu bym poprawił na zmienną adekwatną do komponentu zgodnie z przyjętą konwencją

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +  color: #fff;
Ooops

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +      border-right: 26px solid $text-color;
Tutaj też można to poprawić na bardziej informatywną nazwę zmiennej

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +      border-right: 26px solid $text-color;
Same story

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +      border-right: 26px solid $text-color;
And again

2023-06-16 06:11 UTC, jerzy-jarczynski commented on src/components/layout/Gallery/GallerySlider.module.scss
> +      border-right: 26px solid $text-color;
And again

2023-06-16 16:07 UTC, ZukAd14 requested changes

2023-06-16 16:07 UTC, ZukAd14 commented on src/styles/settings.scss
> +
tego typu zmiennie dorzuć do sekcji "Do not use" ponieważ jeżeli ktoś inny będzie chciał z tego skorzystać gdzieś wyżej to dostanie "undefined"

2023-06-18 18:15 UTC, ZukAd14 requested changes
Popraw poniższe drobnice i jak dla mnie git :)

2023-06-18 18:15 UTC, ZukAd14 commented on src/components/layout/Gallery/Gallery.module.scss
> +    color: $green;
Powinna być zmienna `$gallery-button`

2023-06-18 18:15 UTC, ZukAd14 commented on src/components/layout/Gallery/Gallery.module.scss
> +    background-color: $green;
jw

2023-06-18 18:15 UTC, ZukAd14 commented on src/components/layout/Gallery/GallerySlider.module.scss
> +      background-color: $gallery-border;
Jak dla mnie to trochę za ciemny kolor, ciężko jest przeczytać nazwę kategorii no i według designu też jest jaśniej

2023-06-18 18:15 UTC, ZukAd14 commented on src/components/layout/Gallery/GallerySlider.module.scss
> +
według mnie są za duże odstępy między buttonami

2023-06-18 18:15 UTC, ZukAd14 commented on src/styles/settings.scss
> +$creamy-pink: #ffc2cd;
to jest zadeklarowane dwa razy

2023-06-19 12:17 UTC, iiimoood submitted a review, later dismissed

2023-06-22 05:37 UTC, closed without merging