[Task-WDP230601-40] Widok kategorii produktowej
matwjablonski/wdp-2306-01 pull request #37
Opened 2023-06-20 19:47 UTC by ZukAd14

[Podgląd zadania w Jira](https://projects.kodilla.com/browse/WDP230601-40)

- Stworzyłem stronę kategorii pod adresem `/category/nazwaKategorii`
- Design bazuję na widoku wyszukiwania produktów
- W momencie wpisania w adresie niepełnej nazwy lub błędnej zostaje wyświetlona informacja o braku dopasowań
- Zadanie jest dosyć skromne i nic takiego nie precyzuję jednak nie widzę innego taska z tym związanego więc dodałem przekierowania do przycisków na górze strony oraz rozwijanym kategoriom w select obok wyszukiwarki
- Nie wszystkie przyciski mają odpowiadające im kategorie w `initialState` ale traktuję to jako myślenie przyszłościowe czego uczy kurs
- Musiałem zmodyfikować `categoriesRedux` oraz `productRedux`

2023-06-21 10:03 UTC, Blackbirdev approved these changes

2023-06-21 16:45 UTC, jerzy-jarczynski approved these changes

2023-06-22 17:18 UTC, Blackbirdev submitted a review, later dismissed

2023-06-22 19:33 UTC, Blackbirdev approved these changes

2023-06-22 19:41 UTC, jerzy-jarczynski requested changes
kategorie w rozwijanej liście mają teraz inny kolor i na hover napis przestaje być widoczny

2023-06-23 06:01 UTC, jerzy-jarczynski approved these changes

2023-06-23 16:36 UTC, jerzy-jarczynski approved these changes

2023-06-23 18:11 UTC, iiimoood approved these changes

2023-06-23 20:27 UTC, Blackbirdev approved these changes

2023-06-23 22:28 UTC, Mikaaa366 approved these changes

2023-06-24 20:27 UTC, merged