Bug wdp230601 3
matwjablonski/wdp-2306-01 pull request #4
Opened 2023-06-07 17:04 UTC by ZukAd14

2023-06-08 14:28 UTC, iiimoood submitted a review, later dismissed

2023-06-08 18:49 UTC, jerzy-jarczynski approved these changes
Wygląda w porządku.

2023-06-08 18:49 UTC, jerzy-jarczynski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> -  &.active {
Wydaje mi się, że style dla aktywnego elementu mogłyby być wykorzystane po okodowaniu przechodzenia na podstrony, żeby zaznaczyć podstronę, na której aktualnie się przebywa, ale to zależy od rozwoju projektu.

2023-06-08 18:49 UTC, jerzy-jarczynski commented on src/styles/settings.scss
> +$color-light: #ffffff;
Tu mogą być konflikty do rozwiązania. U siebie również mam ingerencję w settings.

2023-06-08 18:49 UTC, jerzy-jarczynski commented on src/styles/settings.scss
> +$featureBox-border-color: #b6b6b6
Nazwa zmiennej mogłaby być bardziej ogólna. Ten kolor może pojawić się gdzieś jeszcze i nie być związany z featureBox i border.

2023-06-08 19:09 UTC, wilgakuba commented on src/styles/settings.scss
> +$featureBox-border-color: #b6b6b6
-najlepiej nadać nazwę dla koloru np. $mist-gray: #b6b6b6;
-później przypisać go do: $feature-border-color: $mist-gray.
Wtedy gdy kolor pojawi się innym miejscu będzie można ponownie użyć go w ten sam sposób :).

2023-06-08 19:40 UTC, jerzy-jarczynski commented on src/styles/settings.scss
> +$featureBox-border-color: #b6b6b6
Widziałem taska ze zmianami kodów na zmienne, gdzie to było zastosowane i ma to sens.

2023-06-09 07:01 UTC, matwjablonski requested changes

2023-06-09 07:01 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.js
> +      <a href='#'>{children}</a>
w zasadzie mamy tutaj react i react-router-dom - zatem większość linków w aplikacji będzie linkami wewnętrznymi - zamiast `a` wykorzystaj `Link`

2023-06-09 07:01 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +
zbędna pusta linia

2023-06-09 07:01 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +  &:hover {
brakuje linii przerwy pomiędzy selektorami

2023-06-09 07:01 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +    a {
jw.

2023-06-09 07:01 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +
zbędna linia

2023-06-09 08:05 UTC, ZukAd14 commented on src/styles/settings.scss
> +$featureBox-border-color: #b6b6b6
Wtedy jeszcze nie był zmieniony settings.scss, pozmieniałem tak jest w głównym pliku, zaraz zacommituję

2023-06-09 08:08 UTC, ZukAd14 commented on src/components/common/FeatureBox/FeatureBox.js
> +      <a href='#'>{children}</a>
Zmieniłem na komponent Link oraz poprawiłem stylowanie pliku .scss

2023-06-10 18:23 UTC, Blackbirdev submitted a review, later dismissed

2023-06-13 09:02 UTC, iiimoood approved these changes

2023-06-13 12:09 UTC, wilgakuba approved these changes

2023-06-13 18:23 UTC, matwjablonski approved these changes

2023-06-13 18:23 UTC, merged