bug-WDP230601-45
matwjablonski/wdp-2306-01 pull request #50
Opened 2023-06-25 17:59 UTC by jerzy-jarczynski

https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=218&view=detail&selectedIssue=WDP230601-45

**Zamiana BrowserRouter na HashRouter**

- zmieniłem BrowserRouter na HashRouter
- zmieniłem ścieżkę URL do strony wyszukiwarki

Pracuję nad rozwiązaniem, jeszcze nie proszę o CR

2023-06-26 22:17 UTC, ZukAd14 requested changes
Jest konflikt z yarn.lock więc przy okazji podrzucam dwie rzeczy do zmianki, jednak w komentarzu poniżej, druga jest w linijce 100 w productSearch, nie mogę tam dodać komentarza. Trzeba zmienić linijkę `to={`/search/${search.searchContent}`}` na `to={`/search/?s=${search.searchContent}`}` bo inaczej nie działa przenoszenie na stronę wyszukiwania po kliknięciu elementu z listy

2023-06-26 22:17 UTC, ZukAd14 commented on src/components/features/ProductSearch/ProductSearch.js
> -    dispatch(addSearch({ searchContent: activeSearch }));
Przez skasowanie tej linijki nie działa dodawanie wyszukiwań do listy, trzeba ją dodać

2023-06-27 16:59 UTC, ZukAd14 approved these changes

2023-06-27 17:02 UTC, iiimoood approved these changes

2023-06-27 17:49 UTC, merged