WDP230601-6
matwjablonski/wdp-2306-01 pull request #7
Opened 2023-06-07 20:34 UTC by Mikaaa366

link do Jiry: 
https://projects.kodilla.com/browse/WDP230601-6
Opis:
Dodałam drugą cenę "starą" + style, tak, żeby była przekreślona.

2023-06-08 07:03 UTC, ZukAd14 submitted a review, later dismissed
Poza kolorami jako hexy zamiast zmiennych dla mnie ok

2023-06-08 09:54 UTC, Blackbirdev approved these changes

2023-06-08 18:55 UTC, jerzy-jarczynski requested changes
Wymaga sprawdzenia

2023-06-08 18:55 UTC, jerzy-jarczynski commented on src/components/common/ProductBox/ProductBox.js
> +  const oldPricing = oldPrice;
Nie jestem pewien czy taki zabieg jest potrzebny

2023-06-08 18:55 UTC, jerzy-jarczynski commented on src/components/common/ProductBox/ProductBox.js
> +          {oldPricing ? (
Czy testowałeś to bez dodatkowej stałej? Tylko z wykorzystaniem prarametru oldPrice z Props?

2023-06-08 18:55 UTC, jerzy-jarczynski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    text-decoration-color: #000;
kody kolorów trzeba zamienić na nazwy zmiennych z pliku settings.scss

2023-06-08 20:42 UTC, Mikaaa366 commented on src/components/common/ProductBox/ProductBox.js
> +          {oldPricing ? (
tak, ale ma się wyświetlać tylko na niektórych kartach i to jedyny sposób, który znalazłam.

2023-06-08 20:48 UTC, Mikaaa366 commented on src/components/common/ProductBox/ProductBox.module.scss
> +    text-decoration-color: #000;
ok, zmienione

2023-06-08 20:56 UTC, jerzy-jarczynski approved these changes

2023-06-09 06:02 UTC, Blackbirdev commented on src/components/common/ProductBox/ProductBox.js
> +          {oldPricing ? (
A gdybyśmy zrezygnowali z dodatkowej stałej, a w divie z ceną bezpośrednio wykorzystali parametr oldPrice?

`<div className={styles.price}>
{oldPrice && <p>${oldPrice}</p>} `

2023-06-10 07:19 UTC, iiimoood approved these changes

2023-06-10 12:22 UTC, jerzy-jarczynski approved these changes

2023-06-11 17:58 UTC, wilgakuba submitted a review, later dismissed

2023-06-13 07:56 UTC, ZukAd14 submitted a review, later dismissed

2023-06-13 18:46 UTC, Mikaaa366 commented on src/styles/settings.scss
> +$white: #ffffff;
czy teraz jest ok ?

2023-06-13 21:21 UTC, ZukAd14 commented on src/styles/settings.scss
> +$white: #ffffff;
Super ;)

2023-06-13 21:22 UTC, ZukAd14 approved these changes

2023-06-14 19:29 UTC, jerzy-jarczynski approved these changes

2023-06-15 06:54 UTC, merged