bug-WDP230601-4
matwjablonski/wdp-2306-01 pull request #8
Opened 2023-06-08 06:07 UTC by iiimoood

https://projects.kodilla.com/browse/WDP230601-4
Usunęłam atrybut noHover z Buttona, ukryłam przyciski za pomocą stylu przy normalnym wyświetleniu strony i dodałam style dla :hover, by pokazać przyciski i zmienić cenę.

2023-06-08 07:05 UTC, ZukAd14 submitted a review, later dismissed

2023-06-08 08:19 UTC, wilgakuba submitted a review, later dismissed

2023-06-08 18:58 UTC, jerzy-jarczynski submitted a review, later dismissed
Wygląda w porządku

2023-06-09 07:06 UTC, matwjablonski requested changes
po najechaniu na element cały widok skacze, może lepiej zamiast `display: none;` użyć innego sposobu na ukrycie buttonów lub pobawić się `position`

2023-06-10 18:43 UTC, Blackbirdev submitted a review, later dismissed
widok nie skacze, dla mnie w porządku

2023-06-11 17:59 UTC, wilgakuba approved these changes

2023-06-11 19:42 UTC, jerzy-jarczynski commented
Czy tylko u mnie na podglądzie produkty zwiekszają skokowo wysokość na hover kiedy pokazują się te elementy?

2023-06-11 21:22 UTC, ZukAd14 commented
> Czy tylko u mnie na podglądzie produkty zwiekszają skokowo wysokość na hover kiedy pokazują się te elementy?

No właśnie o to mi chodziło komentarz wyżej

2023-06-12 06:22 UTC, matwjablonski commented
Problem nadal występuje.

2023-06-13 08:44 UTC, ZukAd14 approved these changes

2023-06-13 08:49 UTC, Blackbirdev approved these changes

2023-06-13 18:26 UTC, matwjablonski approved these changes

2023-06-13 18:26 UTC, merged